
console.log("INIT: Starting seed script...");
import dotenv from 'dotenv';
import path from 'path';
import mongoose from 'mongoose';
import connectDB from '../mongodb/db';
import Template from '../mongodb/models/Template';

// Force load env from current directory
dotenv.config({ path: path.resolve(process.cwd(), '.env') });
console.log("ENV LOADED. Mono URI present:", !!process.env.MONGODB_URI);


// Copied from template-config.ts to ensure robust seeding without module issues
const TEMPLATES = [
    // SKILLED & FIELD WORK
    {
        id: "electrician",
        name: "Electrician Job",
        description: "Verify electrical installation, repairs, and safety checks",
        category: "Skilled & Field Work",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Job Assigned",
                description: "Confirm job assignment and initial briefing",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "📋",
            },
            {
                id: "step-2",
                name: "Before-Work Photo",
                description: "Upload photo of the work area before starting",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "📸",
            },
            {
                id: "step-3",
                name: "Work In Progress",
                description: "Document work being performed with photo/video",
                order: 3,
                isRequired: true,
                proofType: "photo",
                icon: "🔧",
            },
            {
                id: "step-4",
                name: "Work Completed Photo",
                description: "Upload final photo of completed work",
                order: 4,
                isRequired: true,
                proofType: "photo",
                icon: "✅",
            },
            {
                id: "step-5",
                name: "Client Confirmation",
                description: "Get client sign-off and approval",
                order: 5,
                isRequired: true,
                proofType: "photo",
                icon: "👤",
            },
        ],
    },
    {
        id: "plumber",
        name: "Plumber Job",
        description: "Document pipe installation and repair work",
        category: "Skilled & Field Work",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Site Inspection",
                description: "Document existing conditions with photos",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "🔍",
            },
            {
                id: "step-2",
                name: "Work in Progress",
                description: "Capture installation/repair work",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "🔧",
            },
            {
                id: "step-3",
                name: "Final Installation",
                description: "Photo of completed plumbing work",
                order: 3,
                isRequired: true,
                proofType: "photo",
                icon: "✅",
            },
            {
                id: "step-4",
                name: "Client Approval",
                description: "Get client sign-off",
                order: 4,
                isRequired: true,
                proofType: "photo",
                icon: "👤",
            },
        ],
    },
    {
        id: "carpenter",
        name: "Carpenter Job",
        description: "Verify furniture installation and carpentry work",
        category: "Skilled & Field Work",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Measurement & Planning",
                description: "Document measurements and design",
                order: 1,
                isRequired: true,
                proofType: "both",
                icon: "📐",
            },
            {
                id: "step-2",
                name: "Before Photos",
                description: "Space before work begins",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "📸",
            },
            {
                id: "step-3",
                name: "Installation Progress",
                description: "Work in progress documentation",
                order: 3,
                isRequired: true,
                proofType: "photo",
                icon: "🔨",
            },
            {
                id: "step-4",
                name: "Completed Work",
                description: "Final installation photos",
                order: 4,
                isRequired: true,
                proofType: "photo",
                icon: "✅",
            },
            {
                id: "step-5",
                name: "Client Handover",
                description: "Final approval and sign-off",
                order: 5,
                isRequired: true,
                proofType: "photo",
                icon: "👤",
            },
        ],
    },
    {
        id: "technician",
        name: "Technician Job",
        description: "Document device installation and support work",
        category: "Skilled & Field Work",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Site Assessment",
                description: "Evaluate installation location",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "📊",
            },
            {
                id: "step-2",
                name: "Installation",
                description: "Document installation process",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "⚙️",
            },
            {
                id: "step-3",
                name: "Testing & Validation",
                description: "Verify system functionality",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "✓",
            },
            {
                id: "step-4",
                name: "Client Training",
                description: "Document training completion",
                order: 4,
                isRequired: true,
                proofType: "photo",
                icon: "📚",
            },
        ],
    },
    {
        id: "mechanic",
        name: "Mechanic Job",
        description: "Verify vehicle service and repairs",
        category: "Skilled & Field Work",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Vehicle Inspection",
                description: "Pre-service vehicle photos",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "🔍",
            },
            {
                id: "step-2",
                name: "Service Work",
                description: "Document service/repair work",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "🔧",
            },
            {
                id: "step-3",
                name: "Parts Replacement",
                description: "Before/after photos of parts",
                order: 3,
                isRequired: true,
                proofType: "photo",
                icon: "🛠️",
            },
            {
                id: "step-4",
                name: "Quality Check",
                description: "Final quality assurance",
                order: 4,
                isRequired: true,
                proofType: "photo",
                icon: "✅",
            },
            {
                id: "step-5",
                name: "Customer Approval",
                description: "Get customer sign-off",
                order: 5,
                isRequired: true,
                proofType: "photo",
                icon: "👤",
            },
        ],
    },

    // BUSINESS & CLIENT DELIVERY
    {
        id: "client-deliverable",
        name: "Client Deliverable Workflow",
        description: "Verify client project completion with evidence",
        category: "Business & Client Delivery",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Requirement Confirmation",
                description: "Confirm all client requirements are understood",
                order: 1,
                isRequired: true,
                proofType: "both",
                icon: "📝",
            },
            {
                id: "step-2",
                name: "Work Execution",
                description: "Complete the deliverable work",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "⚙️",
            },
            {
                id: "step-3",
                name: "Internal Review",
                description: "Internal quality assurance and review",
                order: 3,
                isRequired: true,
                proofType: "pdf",
                icon: "🔍",
            },
            {
                id: "step-4",
                name: "Client Delivery",
                description: "Deliver final deliverable to client",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "📦",
            },
            {
                id: "step-5",
                name: "Client Acknowledgment",
                description: "Receive client sign-off and approval",
                order: 5,
                isRequired: true,
                proofType: "both",
                icon: "✔️",
            },
        ],
    },
    {
        id: "invoice-payment",
        name: "Invoice & Payment Proof",
        description: "Document invoice issuance and payment receipt",
        category: "Business & Client Delivery",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Invoice Generated",
                description: "Upload generated invoice document",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "🧾",
            },
            {
                id: "step-2",
                name: "Invoice Sent to Client",
                description: "Confirm invoice delivery to client",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "📧",
            },
            {
                id: "step-3",
                name: "Payment Received Proof",
                description: "Upload payment receipt or bank confirmation",
                order: 3,
                isRequired: true,
                proofType: "pdf",
                icon: "💰",
            },
            {
                id: "step-4",
                name: "Payment Logged",
                description: "Confirm payment recorded in accounting system",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "📊",
            },
        ],
    },
    {
        id: "service-fulfillment",
        name: "Service Fulfillment",
        description: "Track service delivery completion",
        category: "Business & Client Delivery",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Service Booked",
                description: "Confirm service booking details",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📅",
            },
            {
                id: "step-2",
                name: "Service Delivery",
                description: "Document service provision",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "🎯",
            },
            {
                id: "step-3",
                name: "Quality Verification",
                description: "Verify service quality",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "⭐",
            },
            {
                id: "step-4",
                name: "Client Satisfaction",
                description: "Get client feedback and approval",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "😊",
            },
        ],
    },
    {
        id: "vendor-completion",
        name: "Vendor Work Completion",
        description: "Verify external vendor deliverables",
        category: "Business & Client Delivery",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Work Order",
                description: "Vendor work order and specifications",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📄",
            },
            {
                id: "step-2",
                name: "Work in Progress",
                description: "Status updates and photos",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "⏳",
            },
            {
                id: "step-3",
                name: "Deliverable Submission",
                description: "Final deliverable from vendor",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "📦",
            },
            {
                id: "step-4",
                name: "Acceptance",
                description: "Acceptance and verification",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "✓",
            },
        ],
    },
    {
        id: "consulting",
        name: "Consulting Engagement",
        description: "Document consulting project completion",
        category: "Business & Client Delivery",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Scope Agreement",
                description: "Agreed scope and deliverables",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📋",
            },
            {
                id: "step-2",
                name: "Discovery Phase",
                description: "Document discovery findings",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "🔎",
            },
            {
                id: "step-3",
                name: "Analysis & Recommendations",
                description: "Share analysis and recommendations",
                order: 3,
                isRequired: true,
                proofType: "pdf",
                icon: "📊",
            },
            {
                id: "step-4",
                name: "Implementation",
                description: "Document implementation work",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "🛠️",
            },
            {
                id: "step-5",
                name: "Final Report",
                description: "Deliver final report and sign-off",
                order: 5,
                isRequired: true,
                proofType: "pdf",
                icon: "📈",
            },
        ],
    },

    // FREELANCERS & CREATORS
    {
        id: "web-development",
        name: "Website Development Project",
        description: "Track web development project milestones",
        category: "Freelancers & Creators",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Project Setup",
                description: "Initial project setup and repository",
                order: 1,
                isRequired: true,
                proofType: "both",
                icon: "🚀",
            },
            {
                id: "step-2",
                name: "Design Mockups",
                description: "Share design mockups with client",
                order: 2,
                isRequired: true,
                proofType: "pdf",
                icon: "🎨",
            },
            {
                id: "step-3",
                name: "Development Work",
                description: "Code repository and progress updates",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "💻",
            },
            {
                id: "step-4",
                name: "Testing & QA",
                description: "Testing documentation and results",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "✓",
            },
            {
                id: "step-5",
                name: "Deployment & Launch",
                description: "Site deployment and launch proof",
                order: 5,
                isRequired: true,
                proofType: "photo",
                icon: "🎉",
            },
        ],
    },
    {
        id: "app-development",
        name: "App Development Project",
        description: "Verify app development milestones",
        category: "Freelancers & Creators",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Requirements Review",
                description: "App requirements document",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📋",
            },
            {
                id: "step-2",
                name: "Architecture Design",
                description: "Technical architecture documentation",
                order: 2,
                isRequired: true,
                proofType: "pdf",
                icon: "🏗️",
            },
            {
                id: "step-3",
                name: "Development Sprint",
                description: "Code commits and feature demos",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "⚡",
            },
            {
                id: "step-4",
                name: "Beta Testing",
                description: "Beta testing results and feedback",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "🧪",
            },
            {
                id: "step-5",
                name: "App Release",
                description: "App store submission and release",
                order: 5,
                isRequired: true,
                proofType: "photo",
                icon: "📱",
            },
        ],
    },
    {
        id: "graphic-design",
        name: "Graphic Design Delivery",
        description: "Document design project completion",
        category: "Freelancers & Creators",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Brand Brief",
                description: "Brand guidelines and requirements",
                order: 1,
                isRequired: true,
                proofType: "both",
                icon: "📖",
            },
            {
                id: "step-2",
                name: "Design Concepts",
                description: "Share design concepts and drafts",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "🎨",
            },
            {
                id: "step-3",
                name: "Revisions & Finalization",
                description: "Final design files and revisions",
                order: 3,
                isRequired: true,
                proofType: "pdf",
                icon: "✏️",
            },
            {
                id: "step-4",
                name: "Final Delivery",
                description: "High-resolution files and brand assets",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "📦",
            },
        ],
    },
    {
        id: "video-editing",
        name: "Video Editing Project",
        description: "Verify video editing and post-production",
        category: "Freelancers & Creators",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Raw Footage Review",
                description: "Footage organization and cataloging",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "🎬",
            },
            {
                id: "step-2",
                name: "Editing Draft",
                description: "First editing draft for review",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "✂️",
            },
            {
                id: "step-3",
                name: "Color & Sound",
                description: "Color grading and sound design",
                order: 3,
                isRequired: true,
                proofType: "photo",
                icon: "🎵",
            },
            {
                id: "step-4",
                name: "Final Export",
                description: "Final video file delivery",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "📹",
            },
        ],
    },
    {
        id: "content-writing",
        name: "Content Writing Assignment",
        description: "Verify content writing completion",
        category: "Freelancers & Creators",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Content Outline",
                description: "Outline and topic structure",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📝",
            },
            {
                id: "step-2",
                name: "First Draft",
                description: "Initial content draft",
                order: 2,
                isRequired: true,
                proofType: "pdf",
                icon: "✍️",
            },
            {
                id: "step-3",
                name: "Revisions",
                description: "Incorporate feedback and revisions",
                order: 3,
                isRequired: true,
                proofType: "pdf",
                icon: "🔄",
            },
            {
                id: "step-4",
                name: "Final Submission",
                description: "Final polished content",
                order: 4,
                isRequired: true,
                proofType: "pdf",
                icon: "✓",
            },
        ],
    },

    // CONSTRUCTION & INFRASTRUCTURE
    {
        id: "site-inspection",
        name: "Site Inspection Task",
        description: "Document construction site inspections",
        category: "Construction & Infrastructure",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Pre-Inspection",
                description: "Site overview photos",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "📍",
            },
            {
                id: "step-2",
                name: "Detailed Inspection",
                description: "Detailed area inspection photos",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "🔍",
            },
            {
                id: "step-3",
                name: "Issues & Findings",
                description: "Document any issues found",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "⚠️",
            },
            {
                id: "step-4",
                name: "Inspection Report",
                description: "Formal inspection report",
                order: 4,
                isRequired: true,
                proofType: "pdf",
                icon: "📋",
            },
        ],
    },
    {
        id: "construction-phase",
        name: "Construction Phase Completion",
        description: "Verify construction phase milestones",
        category: "Construction & Infrastructure",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Phase Start",
                description: "Phase initiation documentation",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "🚧",
            },
            {
                id: "step-2",
                name: "Progress Photos",
                description: "Regular progress documentation",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "📷",
            },
            {
                id: "step-3",
                name: "Quality Checks",
                description: "Quality assurance inspections",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "✓",
            },
            {
                id: "step-4",
                name: "Phase Completion",
                description: "Phase completion photos",
                order: 4,
                isRequired: true,
                proofType: "photo",
                icon: "✅",
            },
            {
                id: "step-5",
                name: "Sign-Off",
                description: "Client/inspector sign-off",
                order: 5,
                isRequired: true,
                proofType: "both",
                icon: "👤",
            },
        ],
    },
    {
        id: "material-delivery",
        name: "Material Delivery Verification",
        description: "Verify material delivery and acceptance",
        category: "Construction & Infrastructure",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Delivery Notice",
                description: "Delivery notice and documentation",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📬",
            },
            {
                id: "step-2",
                name: "Material Inspection",
                description: "Material condition photos",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "📦",
            },
            {
                id: "step-3",
                name: "Quantity Verification",
                description: "Quantity verification photos",
                order: 3,
                isRequired: true,
                proofType: "photo",
                icon: "📊",
            },
            {
                id: "step-4",
                name: "Acceptance",
                description: "Signed acceptance document",
                order: 4,
                isRequired: true,
                proofType: "pdf",
                icon: "✓",
            },
        ],
    },
    {
        id: "safety-compliance",
        name: "Safety Compliance Check",
        description: "Document safety compliance verification",
        category: "Construction & Infrastructure",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Compliance Review",
                description: "Review compliance requirements",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📋",
            },
            {
                id: "step-2",
                name: "Site Assessment",
                description: "Site safety assessment photos",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "⛑️",
            },
            {
                id: "step-3",
                name: "Corrective Actions",
                description: "Any corrective actions taken",
                order: 3,
                isRequired: false,
                proofType: "both",
                icon: "🔧",
            },
            {
                id: "step-4",
                name: "Compliance Sign-Off",
                description: "Safety compliance certification",
                order: 4,
                isRequired: true,
                proofType: "pdf",
                icon: "✓",
            },
        ],
    },

    // SALES, OPERATIONS, OFFICE
    {
        id: "sales-followup",
        name: "Sales Lead Follow-up",
        description: "Document sales lead follow-up activities",
        category: "Sales / Operations / Office Work",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Lead Contact",
                description: "Initial contact documentation",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📞",
            },
            {
                id: "step-2",
                name: "Meeting/Call",
                description: "Meeting notes or call recording",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "🤝",
            },
            {
                id: "step-3",
                name: "Follow-up Actions",
                description: "Completed follow-up actions",
                order: 3,
                isRequired: true,
                proofType: "pdf",
                icon: "✉️",
            },
            {
                id: "step-4",
                name: "Status Update",
                description: "Lead status update",
                order: 4,
                isRequired: true,
                proofType: "pdf",
                icon: "📈",
            },
        ],
    },
    {
        id: "marketing-campaign",
        name: "Marketing Campaign Execution",
        description: "Track marketing campaign completion",
        category: "Sales / Operations / Office Work",
        stepCount: 5,
        steps: [
            {
                id: "step-1",
                name: "Campaign Plan",
                description: "Campaign strategy and plan",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📋",
            },
            {
                id: "step-2",
                name: "Asset Creation",
                description: "Marketing assets and content",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "🎨",
            },
            {
                id: "step-3",
                name: "Campaign Launch",
                description: "Campaign launch proof",
                order: 3,
                isRequired: true,
                proofType: "photo",
                icon: "🚀",
            },
            {
                id: "step-4",
                name: "Performance Tracking",
                description: "Analytics and performance data",
                order: 4,
                isRequired: true,
                proofType: "pdf",
                icon: "📊",
            },
            {
                id: "step-5",
                name: "Campaign Report",
                description: "Final campaign report",
                order: 5,
                isRequired: true,
                proofType: "pdf",
                icon: "📈",
            },
        ],
    },
    {
        id: "daily-operations",
        name: "Daily Operations Task",
        description: "Document daily operational tasks",
        category: "Sales / Operations / Office Work",
        stepCount: 3,
        steps: [
            {
                id: "step-1",
                name: "Task Start",
                description: "Confirm task assignment",
                order: 1,
                isRequired: true,
                proofType: "photo",
                icon: "🎯",
            },
            {
                id: "step-2",
                name: "Task Execution",
                description: "Document work progress",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "⚙️",
            },
            {
                id: "step-3",
                name: "Task Completion",
                description: "Completion and sign-off",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "✓",
            },
        ],
    },
    {
        id: "field-visit",
        name: "Field Visit Report",
        description: "Document field visit activities",
        category: "Sales / Operations / Office Work",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Visit Purpose",
                description: "Visit objectives and agenda",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📝",
            },
            {
                id: "step-2",
                name: "Site Photos",
                description: "Field visit photos",
                order: 2,
                isRequired: true,
                proofType: "photo",
                icon: "📷",
            },
            {
                id: "step-3",
                name: "Observations",
                description: "Detailed observations and findings",
                order: 3,
                isRequired: true,
                proofType: "pdf",
                icon: "📋",
            },
            {
                id: "step-4",
                name: "Action Items",
                description: "Action items and next steps",
                order: 4,
                isRequired: true,
                proofType: "pdf",
                icon: "✉️",
            },
        ],
    },

    // GENERAL PURPOSE
    {
        id: "daily-worklog",
        name: "Daily Work Log",
        description: "Simple daily task and activity logging",
        category: "General Purpose",
        stepCount: 2,
        steps: [
            {
                id: "step-1",
                name: "Daily Activities",
                description: "Document daily activities",
                order: 1,
                isRequired: true,
                proofType: "both",
                icon: "📝",
            },
            {
                id: "step-2",
                name: "Completion",
                description: "Daily summary and completion",
                order: 2,
                isRequired: true,
                proofType: "pdf",
                icon: "✓",
            },
        ],
    },
    {
        id: "multistep-task",
        name: "Multi-Step Personal Task",
        description: "Flexible template for personal projects",
        category: "General Purpose",
        stepCount: 4,
        steps: [
            {
                id: "step-1",
                name: "Step 1: Planning",
                description: "Plan and organize the task",
                order: 1,
                isRequired: true,
                proofType: "both",
                icon: "📋",
            },
            {
                id: "step-2",
                name: "Step 2: Execution",
                description: "Execute the planned task",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "🔨",
            },
            {
                id: "step-3",
                name: "Step 3: Review",
                description: "Review your work",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "🔍",
            },
            {
                id: "step-4",
                name: "Step 4: Completion",
                description: "Finalize and mark complete",
                order: 4,
                isRequired: true,
                proofType: "both",
                icon: "✓",
            },
        ],
    },
    {
        id: "proof-based-generic",
        name: "Proof-Based Task (Generic)",
        description: "Generic template with simple proof upload",
        category: "General Purpose",
        stepCount: 3,
        steps: [
            {
                id: "step-1",
                name: "Task Definition",
                description: "Define the task",
                order: 1,
                isRequired: true,
                proofType: "pdf",
                icon: "📝",
            },
            {
                id: "step-2",
                name: "Work Evidence",
                description: "Upload proof of work",
                order: 2,
                isRequired: true,
                proofType: "both",
                icon: "📦",
            },
            {
                id: "step-3",
                name: "Verification",
                description: "Verify and complete task",
                order: 3,
                isRequired: true,
                proofType: "both",
                icon: "✓",
            },
        ],
    },
];

async function seedTemplates() {
    try {
        console.log("Connecting to MongoDB...");
        await connectDB();
        console.log("Connected.");

        console.log("Clearing existing templates...");
        await Template.deleteMany({ createdBy: 'system' });

        console.log("Seeding new templates...");
        for (const tpl of TEMPLATES) {
            console.log(`Creating template: ${tpl.name}`);
            await Template.create({
                title: tpl.name,
                description: tpl.description,
                category: tpl.category,
                steps: tpl.steps.map(step => ({
                    id: step.id,
                    name: step.name,
                    description: step.description,
                    required: step.isRequired,
                    proofType: step.proofType,
                    icon: step.icon
                })),
                createdBy: 'system',
                createdAt: new Date()
            });
        }

        console.log("Templates seeded successfully!");
        process.exit(0);
    } catch (error) {
        console.error("Seeding failed:", error);
        process.exit(1);
    }
}

seedTemplates();
